/**
 * Nav2Exporter - turns a Nav2ConfigModel into Nav2-ready YAML and a project JSON.
 *
 * Hand-written emitters (no YAML dependency) because the output structure is
 * fixed and we want full control over Nav2's slightly unusual parameter shapes
 * (e.g. polygon points as a "[[x, y], ...]" string).
 *
 * Target: Nav2 on ROS 2 Humble/Iron/Jazzy. The polygon `points` string form is
 * the one documented for those distros; older distros used a flat float list.
 */
import { driveKind } from './Nav2ConfigModel.js';
import { makeZip } from './zip.js';

function fmt(n) {
    // Compact but unambiguous float formatting.
    if (typeof n !== 'number' || !isFinite(n)) return '0.0';
    if (Number.isInteger(n)) return n.toFixed(1);
    return String(Math.round(n * 1e6) / 1e6);
}

function pointsToString(points) {
    return '[' + points.map(p => `[${fmt(p[0])}, ${fmt(p[1])}]`).join(', ') + ']';
}

export class Nav2Exporter {
    /** Generate collision_monitor.yaml content. */
    static collisionMonitorYaml(config) {
        const enabled = config.polygons.filter(p => p.enabled);
        const names = enabled.map(p => pascal(p.name));

        const L = [];
        L.push('# Generated by Nav2 Editor');
        L.push('# Nav2 Collision Monitor configuration');
        L.push('collision_monitor:');
        L.push('  ros__parameters:');
        L.push(`    base_frame_id: "${config.baseFrame}"`);
        L.push(`    odom_frame_id: "${config.odomFrame}"`);
        L.push('    cmd_vel_in_topic: "cmd_vel_smoothed"');
        L.push('    cmd_vel_out_topic: "cmd_vel"');
        L.push('    state_topic: "collision_monitor_state"');
        L.push(`    transform_tolerance: ${fmt(config.transformTolerance)}`);
        L.push(`    source_timeout: ${fmt(config.sourceTimeout)}`);
        L.push('    base_shift_correction: True');
        L.push('    stop_pub_timeout: 2.0');
        L.push(`    polygons: [${names.map(n => `"${n}"`).join(', ')}]`);

        for (const poly of enabled) {
            const name = pascal(poly.name);
            L.push(`    ${name}:`);
            if (poly.shape === 'circle') {
                L.push('      type: "circle"');
                L.push(`      radius: ${fmt(poly.radius)}`);
            } else {
                L.push('      type: "polygon"');
                if (poly.action_type !== 'approach') {
                    L.push(`      points: "${pointsToString(poly.points)}"`);
                }
            }
            L.push(`      action_type: "${poly.action_type}"`);

            if (poly.action_type === 'slowdown') {
                L.push(`      slowdown_ratio: ${fmt(poly.slowdown_ratio)}`);
            }
            if (poly.action_type === 'limit') {
                L.push(`      linear_limit: ${fmt(poly.linear_limit)}`);
                L.push(`      angular_limit: ${fmt(poly.angular_limit)}`);
            }
            if (poly.action_type === 'approach') {
                // Approach polygons follow the published footprint by default.
                L.push('      footprint_topic: "/local_costmap/published_footprint"');
                L.push(`      time_before_collision: ${fmt(poly.time_before_collision)}`);
                L.push(`      simulation_time_step: ${fmt(poly.simulation_time_step)}`);
            }
            L.push(`      min_points: ${Math.round(poly.min_points)}`);
            L.push(`      visualize: ${poly.visualize ? 'True' : 'False'}`);
            L.push(`      polygon_pub_topic: "${topicName(poly.name)}"`);
            L.push('      enabled: True');
        }

        const sources = config.observationSources;
        L.push(`    observation_sources: [${sources.map(s => `"${s.name}"`).join(', ')}]`);
        for (const s of sources) {
            L.push(`    ${s.name}:`);
            L.push(`      type: "${s.type}"`);
            L.push(`      topic: "${s.topic}"`);
            L.push('      enabled: True');
        }
        L.push('');
        return L.join('\n');
    }

    /** Generate a costmap parameters snippet (global + local). */
    static costmapYaml(config) {
        const c = config.costmap;
        const usePolyFootprint = c.useFootprint || config.footprint.mode === 'polygon';
        const footprintLine = usePolyFootprint
            ? `      footprint: "${pointsToString(config.footprint.points)}"`
            : `      robot_radius: ${fmt(config.footprint.mode === 'radius' ? config.footprint.radius : c.robotRadius)}`;

        const block = (scope) => [
            `${scope}:`,
            `  ${scope}:`,
            '    ros__parameters:',
            `      resolution: ${fmt(c.resolution)}`,
            footprintLine,
            '      inflation_layer:',
            '        plugin: "nav2_costmap_2d::InflationLayer"',
            `        inflation_radius: ${fmt(c.inflationRadius)}`,
            `        cost_scaling_factor: ${fmt(c.costScalingFactor)}`
        ].join('\n');

        return [
            '# Generated by Nav2 Editor',
            '# Costmap footprint / inflation parameters.',
            '# Merge these into your nav2_params.yaml.',
            block('local_costmap'),
            '',
            block('global_costmap'),
            ''
        ].join('\n');
    }

    /** Generate a controller_server.yaml snippet for the selected drive + plugin. */
    static controllerServerYaml(config) {
        const c = config.controller;
        const kind = driveKind(c.driveType);
        const carLike = kind === 'car';
        const holonomic = kind === 'holonomic';

        const L = [];
        L.push('# Generated by Nav2 Editor');
        L.push(`# Drive model: ${c.driveType} · Controller: ${c.plugin.toUpperCase()}`);
        if (c.driveJoints && c.driveJoints.length) {
            L.push(`# Drive joints: ${c.driveJoints.join(', ')}`);
        }
        if (c.steeringJoints && c.steeringJoints.length) {
            L.push(`# Steering joints: ${c.steeringJoints.join(', ')}`);
        }
        if (carLike && c.plugin === 'dwb') {
            L.push('# NOTE: DWB is poorly suited to car-like robots. Prefer Regulated Pure Pursuit or MPPI.');
        }
        L.push('controller_server:');
        L.push('  ros__parameters:');
        L.push('    controller_frequency: 20.0');
        L.push('    controller_plugins: ["FollowPath"]');
        L.push('    FollowPath:');

        if (c.plugin === 'rpp') {
            L.push('      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"');
            L.push(`      desired_linear_vel: ${fmt(c.desiredLinearVel)}`);
            L.push(`      lookahead_dist: ${fmt(c.lookaheadDist)}`);
            L.push('      min_lookahead_dist: 0.3');
            L.push('      max_lookahead_dist: 0.9');
            L.push('      use_velocity_scaled_lookahead_dist: true');
            L.push(`      max_angular_accel: ${fmt(c.maxAccelX)}`);
            L.push(`      allow_reversing: ${c.allowReversing ? 'true' : 'false'}`);
            L.push('      use_regulated_linear_velocity_scaling: true');
            if (carLike) {
                // Car-like robots must not rotate in place; follow the path heading.
                L.push('      use_rotate_to_heading: false');
                if (c.minTurningRadius > 0) {
                    L.push(`      # Min turning radius ${fmt(c.minTurningRadius)} m — ensure your path planner (e.g. Smac Hybrid-A*) respects it.`);
                }
            } else {
                L.push('      use_rotate_to_heading: true');
            }
        } else if (c.plugin === 'dwb') {
            L.push('      plugin: "dwb_core::DWBLocalPlanner"');
            L.push(`      max_vel_x: ${fmt(c.maxVelX)}`);
            L.push(`      min_vel_x: ${fmt(c.minVelX)}`);
            L.push(`      max_vel_theta: ${fmt(c.maxVelTheta)}`);
            L.push(`      max_vel_y: ${fmt(holonomic ? c.maxVelX : 0)}`);
            L.push(`      min_speed_xy: 0.0`);
            L.push(`      max_speed_xy: ${fmt(c.maxVelX)}`);
            L.push(`      acc_lim_x: ${fmt(c.maxAccelX)}`);
            L.push(`      acc_lim_theta: ${fmt(c.maxAccelX * 2)}`);
            L.push('      vx_samples: 20');
            L.push(`      vy_samples: ${holonomic ? '10' : '0'}`);
            L.push('      vtheta_samples: 20');
            L.push('      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]');
        } else if (c.plugin === 'mppi') {
            L.push('      plugin: "nav2_mppi_controller::MPPIController"');
            L.push(`      vx_max: ${fmt(c.maxVelX)}`);
            L.push(`      vx_min: ${fmt(c.minVelX)}`);
            L.push(`      vy_max: ${fmt(holonomic ? c.maxVelX : 0)}`);
            L.push(`      wz_max: ${fmt(c.maxVelTheta)}`);
            const motionModel = carLike ? 'Ackermann' : (holonomic ? 'Omni' : 'DiffDrive');
            L.push(`      motion_model: "${motionModel}"`);
            if (carLike && c.minTurningRadius > 0) {
                L.push('      AckermannConstraints:');
                L.push(`        min_turning_r: ${fmt(c.minTurningRadius)}`);
            }
        } else if (c.plugin === 'graceful') {
            L.push('      plugin: "nav2_graceful_controller::GracefulController"');
            L.push(`      desired_linear_vel: ${fmt(c.desiredLinearVel)}`);
            L.push(`      max_angular_vel: ${fmt(c.maxVelTheta)}`);
        } else if (c.plugin === 'rotation_shim') {
            L.push('      plugin: "nav2_rotation_shim_controller::RotationShimController"');
            L.push('      primary_controller: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"');
            L.push(`      max_angular_accel: ${fmt(c.maxAccelX)}`);
            L.push('      # primary_controller params:');
            L.push(`      desired_linear_vel: ${fmt(c.desiredLinearVel)}`);
            L.push(`      lookahead_dist: ${fmt(c.lookaheadDist)}`);
        }
        L.push('');
        return L.join('\n');
    }

    /** Resolve 'auto' planner to a concrete plugin based on the drive model. */
    static resolvePlanner(config) {
        const p = config.controller.planner;
        if (p && p !== 'auto') return p;
        return driveKind(config.controller.driveType) === 'car' ? 'smac_hybrid' : 'smac2d';
    }

    /** Generate a planner_server block. */
    static plannerServerYaml(config) {
        const plan = this.resolvePlanner(config);
        const c = config.controller;
        const L = [];
        L.push('planner_server:');
        L.push('  ros__parameters:');
        L.push('    expected_planner_frequency: 20.0');
        L.push('    planner_plugins: ["GridBased"]');
        L.push('    GridBased:');
        if (plan === 'smac_hybrid') {
            let r = c.minTurningRadius;
            if (!(r > 0)) r = c.wheelbase > 0 ? Math.round((c.wheelbase / Math.tan(0.6)) * 100) / 100 : 0.4;
            L.push('      plugin: "nav2_smac_planner::SmacPlannerHybrid"');
            L.push('      tolerance: 0.25');
            L.push('      allow_unknown: true');
            L.push('      downsample_costmap: false');
            L.push(`      motion_model_for_search: "${c.allowReversing ? 'REEDS_SHEPP' : 'DUBIN'}"`);
            L.push(`      minimum_turning_radius: ${fmt(r)}`);
            L.push('      angle_quantization_bins: 72');
            L.push('      analytic_expansion_ratio: 3.5');
            L.push('      reverse_penalty: 2.0');
            L.push('      change_penalty: 0.0');
            L.push('      non_straight_penalty: 1.2');
            L.push('      cost_penalty: 2.0');
        } else if (plan === 'smac2d') {
            L.push('      plugin: "nav2_smac_planner::SmacPlanner2D"');
            L.push('      tolerance: 0.125');
            L.push('      allow_unknown: true');
            L.push('      use_final_approach_orientation: false');
        } else {
            L.push('      plugin: "nav2_navfn_planner::NavfnPlanner"');
            L.push('      tolerance: 0.5');
            L.push('      use_astar: true');
            L.push('      allow_unknown: true');
        }
        L.push('');
        return L.join('\n');
    }

    /** Generate a ros2_control controllers.yaml from the selected drive joints. */
    static ros2ControllersYaml(config) {
        const c = config.controller;
        const kind = driveKind(c.driveType);
        const drive = c.driveJoints.slice();
        const steer = c.steeringJoints.slice();
        const L = [];
        L.push('# Generated by Nav2 Editor — ros2_control controllers');
        L.push(`# Drive model: ${c.driveType}`);
        L.push('controller_manager:');
        L.push('  ros__parameters:');
        L.push('    update_rate: 50');
        L.push('    joint_state_broadcaster:');
        L.push('      type: joint_state_broadcaster/JointStateBroadcaster');

        const wheelRadius = 0.1; // placeholder; user should adjust
        if (kind === 'diff') {
            L.push('    diff_drive_controller:');
            L.push('      type: diff_drive_controller/DiffDriveController');
            L.push('');
            const { left, right } = splitLeftRight(drive);
            L.push('diff_drive_controller:');
            L.push('  ros__parameters:');
            L.push(`    left_wheel_names: [${left.map(q).join(', ')}]`);
            L.push(`    right_wheel_names: [${right.map(q).join(', ')}]`);
            L.push(`    wheel_separation: ${fmt(c.wheelbase || 0.4)}  # TODO: set track width`);
            L.push(`    wheel_radius: ${fmt(wheelRadius)}  # TODO`);
            L.push(`    base_frame_id: ${q(config.baseFrame)}`);
            L.push(`    max_velocity: ${fmt(c.maxVelX)}`);
        } else if (c.driveType === 'tricycle') {
            L.push('    tricycle_controller:');
            L.push('      type: tricycle_controller/TricycleController');
            L.push('');
            L.push('tricycle_controller:');
            L.push('  ros__parameters:');
            L.push(`    traction_joint_name: ${q(drive[0] || 'drive_wheel_joint')}`);
            L.push(`    steering_joint_name: ${q(steer[0] || 'steering_joint')}`);
            L.push(`    wheelbase: ${fmt(c.wheelbase || 0.5)}`);
            L.push(`    wheel_radius: ${fmt(wheelRadius)}  # TODO`);
            L.push(`    base_frame_id: ${q(config.baseFrame)}`);
        } else if (kind === 'car') {
            // Ackermann / 4WS -> bicycle/ackermann steering controller
            L.push('    steering_controller:');
            L.push('      type: ackermann_steering_controller/AckermannSteeringController');
            L.push('');
            L.push('steering_controller:');
            L.push('  ros__parameters:');
            L.push(`    rear_wheels_names: [${drive.map(q).join(', ')}]`);
            L.push(`    front_wheels_names: [${steer.map(q).join(', ')}]`);
            L.push(`    wheelbase: ${fmt(c.wheelbase || 0.5)}`);
            L.push(`    front_wheel_track: ${fmt(0.4)}  # TODO`);
            L.push(`    rear_wheel_track: ${fmt(0.4)}   # TODO`);
            L.push(`    front_wheels_radius: ${fmt(wheelRadius)}  # TODO`);
            L.push(`    rear_wheels_radius: ${fmt(wheelRadius)}   # TODO`);
            if (c.driveType === 'four_wheel_steering') {
                L.push('    # NOTE: 4WS has no single standard ros2_control controller.');
                L.push('    # Consider a custom controller driving these steering joints:');
                L.push(`    # steering_joints: [${steer.map(q).join(', ')}]`);
            }
        } else {
            // omni / mecanum / legged
            L.push('    # NOTE: omni/mecanum/legged drives need a custom or mecanum controller.');
            L.push(`    # drive_joints: [${drive.map(q).join(', ')}]`);
        }
        L.push('');
        return L.join('\n');
    }

    /** A minimal launch skeleton that loads the generated params. */
    static bringupLaunchPy() {
        return [
            '# Generated by Nav2 Editor — minimal bringup skeleton',
            'import os',
            'from ament_index_python.packages import get_package_share_directory',
            'from launch import LaunchDescription',
            'from launch_ros.actions import Node',
            '',
            'def generate_launch_description():',
            "    params = os.path.join(os.getcwd(), 'nav2_params.yaml')",
            '    return LaunchDescription([',
            "        Node(package='nav2_controller', executable='controller_server',",
            "             output='screen', parameters=[params]),",
            "        Node(package='nav2_planner', executable='planner_server',",
            "             output='screen', parameters=[params]),",
            "        Node(package='nav2_collision_monitor', executable='collision_monitor',",
            "             output='screen', parameters=[params]),",
            "        # Add bt_navigator, behavior_server, smoother_server, velocity_smoother,",
            "        # map_server, amcl and a lifecycle_manager as needed.",
            '    ])',
            ''
        ].join('\n');
    }

    /** Assemble a single nav2_params.yaml from all the node blocks. */
    static fullNav2ParamsYaml(config) {
        const planLabel = this.resolvePlanner(config);
        const parts = [];
        parts.push('# Generated by Nav2 Editor — combined nav2_params.yaml');
        parts.push(`# Drive: ${config.controller.driveType} · Controller: ${config.controller.plugin.toUpperCase()} · Planner: ${planLabel}`);
        parts.push('# Review TODOs and frame/topic names before use.');
        parts.push('');
        parts.push(this._amclBlock(config));
        parts.push(this._btNavigatorBlock());
        parts.push(this.controllerServerYaml(config));
        parts.push(this.plannerServerYaml(config));
        parts.push(this._smootherBlock());
        parts.push(this._behaviorBlock(config));
        parts.push(this._velocitySmootherBlock(config));
        parts.push(this.costmapYaml(config));
        parts.push(this.collisionMonitorYaml(config));
        parts.push(this._mapServerBlock());
        return parts.join('\n');
    }

    static _amclBlock(config) {
        return [
            'amcl:',
            '  ros__parameters:',
            `    base_frame_id: "${config.baseFrame}"`,
            '    global_frame_id: "map"',
            `    odom_frame_id: "${config.odomFrame}"`,
            '    scan_topic: scan',
            '    robot_model_type: "nav2_amcl::DifferentialMotionModel"',
            ''
        ].join('\n');
    }
    static _btNavigatorBlock() {
        return [
            'bt_navigator:',
            '  ros__parameters:',
            '    global_frame: map',
            '    robot_base_frame: base_link',
            '    odom_topic: /odom',
            ''
        ].join('\n');
    }
    static _smootherBlock() {
        return [
            'smoother_server:',
            '  ros__parameters:',
            '    smoother_plugins: ["simple_smoother"]',
            '    simple_smoother:',
            '      plugin: "nav2_smoother::SimpleSmoother"',
            ''
        ].join('\n');
    }
    static _behaviorBlock(config) {
        return [
            'behavior_server:',
            '  ros__parameters:',
            `    local_frame: ${config.odomFrame}`,
            '    global_frame: map',
            '    robot_base_frame: base_link',
            '    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]',
            ''
        ].join('\n');
    }
    static _velocitySmootherBlock(config) {
        const c = config.controller;
        return [
            'velocity_smoother:',
            '  ros__parameters:',
            `    max_velocity: [${fmt(c.maxVelX)}, 0.0, ${fmt(c.maxVelTheta)}]`,
            `    min_velocity: [${fmt(c.minVelX)}, 0.0, ${fmt(-c.maxVelTheta)}]`,
            `    max_accel: [${fmt(c.maxAccelX)}, 0.0, ${fmt(c.maxAccelX * 2)}]`,
            `    max_decel: [${fmt(-c.maxAccelX)}, 0.0, ${fmt(-c.maxAccelX * 2)}]`,
            ''
        ].join('\n');
    }
    static _mapServerBlock() {
        return [
            'map_server:',
            '  ros__parameters:',
            '    yaml_filename: "map.yaml"',
            ''
        ].join('\n');
    }

    // ==================== costmap filters (keepout / speed zones) ====================

    /** Bounding grid for a set of zones, in the map frame. */
    static _zoneGrid(zones, resolution, margin = 1.0) {
        let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
        for (const z of zones) {
            for (const [x, y] of z.points) {
                minX = Math.min(minX, x); minY = Math.min(minY, y);
                maxX = Math.max(maxX, x); maxY = Math.max(maxY, y);
            }
        }
        if (!isFinite(minX)) { minX = -2; minY = -2; maxX = 2; maxY = 2; }
        minX -= margin; minY -= margin; maxX += margin; maxY += margin;
        const res = resolution > 0 ? resolution : 0.05;
        const width = Math.max(1, Math.ceil((maxX - minX) / res));
        const height = Math.max(1, Math.ceil((maxY - minY) / res));
        return { minX, minY, res, width, height };
    }

    /**
     * Rasterize zones into a PGM (P5) mask.
     * valueFn(zone) -> pixel value (0-255) for cells inside that zone.
     * Cells outside every zone get `outside`.
     */
    static _rasterMask(zones, grid, valueFn, outside) {
        const { minX, minY, res, width, height } = grid;
        const header = `P5\n${width} ${height}\n255\n`;
        const headerBytes = new TextEncoder().encode(header);
        const pixels = new Uint8Array(width * height);
        pixels.fill(outside);

        for (let row = 0; row < height; row++) {
            const wy = minY + (height - 1 - row + 0.5) * res; // image row 0 = top (max y)
            for (let col = 0; col < width; col++) {
                const wx = minX + (col + 0.5) * res;
                for (const z of zones) {
                    if (pointInPolygon(wx, wy, z.points)) {
                        pixels[row * width + col] = valueFn(z);
                        break;
                    }
                }
            }
        }
        const out = new Uint8Array(headerBytes.length + pixels.length);
        out.set(headerBytes, 0);
        out.set(pixels, headerBytes.length);
        return out;
    }

    static _maskYaml(imageName, grid, mode) {
        return [
            `image: ${imageName}`,
            'resolution: ' + fmt(grid.res),
            `origin: [${fmt(grid.minX)}, ${fmt(grid.minY)}, 0.0]`,
            'negate: 0',
            'occupied_thresh: 0.65',
            'free_thresh: 0.25',
            `mode: ${mode}`,
            ''
        ].join('\n');
    }

    /** Keepout mask (occupied=keepout). Returns {pgm, yaml} or null. */
    static keepoutMask(config) {
        const zones = config.zones.filter(z => z.enabled && z.type === 'keepout' && z.points.length >= 3);
        if (!zones.length) return null;
        const grid = this._zoneGrid(zones, config.costmap.resolution);
        const pgm = this._rasterMask(zones, grid, () => 0, 255); // inside=0 (occupied)
        return { pgm, yaml: this._maskYaml('keepout_mask.pgm', grid, 'trinary') };
    }

    /** Speed mask (pixel encodes % speed limit). Returns {pgm, yaml} or null. */
    static speedMask(config) {
        const zones = config.zones.filter(z => z.enabled && z.type === 'speed' && z.points.length >= 3);
        if (!zones.length) return null;
        const grid = this._zoneGrid(zones, config.costmap.resolution);
        // mode "scale": occupancy = (255 - p)/255*100  ->  p = 255 - speed*2.55
        const pgm = this._rasterMask(zones, grid,
            (z) => Math.max(0, Math.min(255, Math.round(255 - (z.speedLimit || 0) * 2.55))), 255);
        return { pgm, yaml: this._maskYaml('speed_mask.pgm', grid, 'scale') };
    }

    /** costmap_filter_info_server + costmap filter plugin snippet for the zones. */
    static costmapFiltersYaml(config) {
        const hasKeepout = config.zones.some(z => z.enabled && z.type === 'keepout');
        const hasSpeed = config.zones.some(z => z.enabled && z.type === 'speed');
        if (!hasKeepout && !hasSpeed) return '';

        const L = ['# Generated by Nav2 Editor — costmap filters'];
        if (hasKeepout) {
            L.push('costmap_filter_info_server:');
            L.push('  ros__parameters:');
            L.push('    type: 0                       # 0 = keepout/preferred lanes');
            L.push('    filter_info_topic: "/costmap_filter_info"');
            L.push('    mask_topic: "/keepout_filter_mask"');
            L.push('    base: 0.0');
            L.push('    multiplier: 1.0');
            L.push('filter_mask_server:');
            L.push('  ros__parameters:');
            L.push('    yaml_filename: "keepout_mask.yaml"');
            L.push('');
        }
        if (hasSpeed) {
            L.push('speed_costmap_filter_info_server:');
            L.push('  ros__parameters:');
            L.push('    type: 1                       # 1 = speed limit (percentage)');
            L.push('    filter_info_topic: "/speed_costmap_filter_info"');
            L.push('    mask_topic: "/speed_filter_mask"');
            L.push('    base: 100.0');
            L.push('    multiplier: -1.0');
            L.push('speed_filter_mask_server:');
            L.push('  ros__parameters:');
            L.push('    yaml_filename: "speed_mask.yaml"');
            L.push('');
        }
        L.push('# Add to local_costmap/global_costmap plugins to apply the filters:');
        if (hasKeepout) {
            L.push('#   keepout_filter:');
            L.push('#     plugin: "nav2_costmap_2d::KeepoutFilter"');
            L.push('#     filter_info_topic: "/costmap_filter_info"');
        }
        if (hasSpeed) {
            L.push('#   speed_filter:');
            L.push('#     plugin: "nav2_costmap_2d::SpeedFilter"');
            L.push('#     filter_info_topic: "/speed_costmap_filter_info"');
            L.push('#     speed_limit_topic: "/speed_limit"');
        }
        L.push('');
        return L.join('\n');
    }

    /** Bundle everything into a downloadable .zip. */
    static downloadBundle(config) {
        const files = [
            { name: 'nav2_params.yaml', content: this.fullNav2ParamsYaml(config) },
            { name: 'ros2_controllers.yaml', content: this.ros2ControllersYaml(config) },
            { name: 'bringup.launch.py', content: this.bringupLaunchPy() },
            { name: 'nav2_project.json', content: this.projectJson(config) }
        ];

        // Costmap filter masks + filters config (only if zones exist).
        const filters = this.costmapFiltersYaml(config);
        if (filters) files.push({ name: 'costmap_filters.yaml', content: filters });
        const keepout = this.keepoutMask(config);
        if (keepout) {
            files.push({ name: 'keepout_mask.pgm', content: keepout.pgm });
            files.push({ name: 'keepout_mask.yaml', content: keepout.yaml });
        }
        const speed = this.speedMask(config);
        if (speed) {
            files.push({ name: 'speed_mask.pgm', content: speed.pgm });
            files.push({ name: 'speed_mask.yaml', content: speed.yaml });
        }
        const blob = makeZip(files);
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'nav2_config.zip';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }

    /**
     * Top-down footprint as an SVG (vector), for use as a base_footprint
     * drawing/template. ROS top view: +x up, +y left. 1 m = 100 px.
     */
    static footprintSvg(config) {
        const fp = config.footprint;
        let pts;
        if (fp.mode === 'polygon' && fp.points.length >= 3) {
            pts = fp.points;
        } else {
            const r = fp.radius || 0.3;
            pts = [];
            for (let i = 0; i < 48; i++) {
                const a = (i / 48) * Math.PI * 2;
                pts.push([Math.cos(a) * r, Math.sin(a) * r]);
            }
        }
        const S = 100; // px per metre
        // ROS top view: screen x = -y (left positive), screen y = -x (forward up).
        const mapped = pts.map(([x, y]) => [-y * S, -x * S]);
        let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
        for (const [sx, sy] of mapped) {
            minX = Math.min(minX, sx); minY = Math.min(minY, sy);
            maxX = Math.max(maxX, sx); maxY = Math.max(maxY, sy);
        }
        const pad = 30;
        minX -= pad; minY -= pad; maxX += pad; maxY += pad;
        const w = (maxX - minX).toFixed(1), h = (maxY - minY).toFixed(1);
        const poly = mapped.map(([sx, sy]) => `${(sx - minX).toFixed(1)},${(sy - minY).toFixed(1)}`).join(' ');
        const ox = (-minX).toFixed(1), oy = (-minY).toFixed(1); // base origin

        return [
            `<?xml version="1.0" encoding="UTF-8"?>`,
            `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">`,
            `  <!-- Nav2 Editor footprint (top view). +x up, +y left, 1 m = ${S}px. base_frame: ${config.baseFrame} -->`,
            `  <rect width="${w}" height="${h}" fill="#ffffff"/>`,
            `  <polygon points="${poly}" fill="#30d15833" stroke="#1a9e3f" stroke-width="2"/>`,
            `  <line x1="${ox}" y1="${oy}" x2="${ox}" y2="${(Number(oy) - 0.5 * S).toFixed(1)}" stroke="#d11" stroke-width="2"/>`,
            `  <text x="${(Number(ox) + 4)}" y="${(Number(oy) - 0.5 * S + 4).toFixed(1)}" font-size="12" fill="#d11">x</text>`,
            `  <circle cx="${ox}" cy="${oy}" r="3" fill="#0a84ff"/>`,
            `</svg>`,
            ''
        ].join('\n');
    }

    /** Serialize the whole project as JSON. */
    static projectJson(config) {
        return JSON.stringify(config.toJSON(), null, 2);
    }

    /** Trigger a browser download (same pattern as CodeEditorManager.downloadFile). */
    static download(content, fileName, mime = 'text/yaml;charset=utf-8') {
        const blob = new Blob([content], { type: mime });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = fileName;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }
}

/** Ray-casting point-in-polygon test. pts: [[x,y],...] */
function pointInPolygon(x, y, pts) {
    let inside = false;
    for (let i = 0, j = pts.length - 1; i < pts.length; j = i++) {
        const xi = pts[i][0], yi = pts[i][1], xj = pts[j][0], yj = pts[j][1];
        const intersect = ((yi > y) !== (yj > y)) &&
            (x < (xj - xi) * (y - yi) / ((yj - yi) || 1e-12) + xi);
        if (intersect) inside = !inside;
    }
    return inside;
}

/** Quote a string for YAML. */
function q(s) {
    return `"${String(s)}"`;
}

/** Split wheel joints into left/right groups (by name, else by halves). */
function splitLeftRight(joints) {
    const left = joints.filter(n => /left|_l\b|_l_|lhs/i.test(n));
    const right = joints.filter(n => /right|_r\b|_r_|rhs/i.test(n));
    if (left.length && right.length) return { left, right };
    const mid = Math.ceil(joints.length / 2);
    return { left: joints.slice(0, mid), right: joints.slice(mid) };
}

/** Sanitize a polygon name into a valid ROS topic (lowercase, underscores). */
function topicName(name) {
    return String(name).toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'polygon';
}

/** Collision Monitor polygon names are conventionally PascalCase identifiers. */
function pascal(name) {
    return String(name)
        .replace(/[^a-zA-Z0-9]+/g, ' ')
        .trim()
        .split(/\s+/)
        .map(w => w.charAt(0).toUpperCase() + w.slice(1))
        .join('') || 'Polygon';
}
